### ISSUE TITLE
[BUG]Conflict with AuthMe

### ISSUE THREAD

**Issue by zhuWin** [zhuWin/Minecraft-Pseudo-localization-Language-Pack#1]
**Version:0.05.230830(Modrinth),0.04.230806(ZWPACK Mizuki Blue R2)**

Conflict with `AuthMe` plugin for unknown reasons.

Players need to switch back to any normal languages to connect any server using AuthMe plugin.

Tested on these server:
* `AriaCraft`
* `神域天堂 (Clover Pixel)`
* `洛花星雨`
* `Remiaft Network`
![AriaCraft](https://img1.imgtp.com/2023/10/01/ivgIducD.png)
![神域天堂](https://img1.imgtp.com/2023/10/01/bs1IMNFq.png)

I don't know why. Weird about just a client side display language can cause a network problem. 

```
[AuthMe] Task #212 for AuthMe v5.4.0-b1877 generated an exception

java.lang.NullPointerException
at java.util.Objects.requireNonNull(Unknown Source) ~[?:1.8.0_341]
at java.util.Arrays$ArrayList.<init>(Unknown Source) ~[?:1.8.0_341]
at java.util.Arrays.asList(Unknown Source) ~[?:1.8.0_341]
at fr.xephi.authme.permission.handlers.VaultHandler.getGroups(VaultHandler.java:79) ~[?:?]
at fr.xephi.authme.permission.handlers.VaultHandler.getGroups(VaultHandler.java:19) ~[?:?]
at fr.xephi.authme.permission.PermissionsManager.getGroups(PermissionsManager.java:295) ~[?:?]
at fr.xephi.authme.data.limbo.LimboServiceHelper.createLimboPlayer(LimboServiceHelper.java:47) ~[?:?]
at fr.xephi.authme.data.limbo.LimboService.createLimboPlayer(LimboService.java:70) ~[?:?]
at fr.xephi.authme.process.join.AsynchronousJoin.lambda$processJoinSync$6(AsynchronousJoin.java:160) ~[?:?]
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[PaperSpigot-1.8.8.jar:git-PaperSpigot-f6fba00-9935adc]
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [PaperSpigot-1.8.8.jar:git-PaperSpigot-f6fba00-9935adc]
at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:779) [PaperSpigot-1.8.8.jar:git-PaperSpigot-f6fba00-9935adc]
at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [PaperSpigot-1.8.8.jar:git-PaperSpigot-f6fba00-9935adc]
at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:710) [PaperSpigot-1.8.8.jar:git-PaperSpigot-f6fba00-9935adc]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:613) [PaperSpigot-1.8.8.jar:git-PaperSpigot-f6fba00-9935adc]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_341]
```

**Comment by zhuWin** [comment]
太棒了，当场爆炸
